jobs:
    include:
      - stage: build docker image
        script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/flightbook-api .
        - docker images
        - docker tag  $DOCKER_USERNAME/flightbook-api:latest $DOCKER_USERNAME/flightbook-api:"$TRAVIS_BUILD_NUMBER"
        - docker push $DOCKER_USERNAME/flightbook-api:"$TRAVIS_BUILD_NUMBER"
        - docker push $DOCKER_USERNAME/flightbook-api:latest
  branches:
    only:
    - master