import { MigrationInterface, QueryRunner } from "typeorm";

export class pg1613943227738 implements MigrationInterface {
    name = 'pg1613943227738'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."place" DROP CONSTRAINT "fk_f932bcc7e17e3673cf5da5d828c"`);
        await queryRunner.query(`ALTER TABLE "public"."glider" DROP CONSTRAINT "fk_19c3b7c7e703ff604bb3e1cfa73"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "fk_5cf201db9ec080554a510914359"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "fk_6e3cf0bb9b6729108a3b1dc2564"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "fk_bec9140d8e19f641e75f5b340c6"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "fk_d4c2b80985553b9400b9898a313"`);
        await queryRunner.query(`ALTER TABLE "public"."glider" RENAME COLUMN "nbflights" TO "nbFlights"`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."place"."id" IS NULL`);
        await queryRunner.query(`CREATE SEQUENCE "public"."place_id_seq" OWNED BY "public"."place"."id"`);
        await queryRunner.query(`SELECT SETVAL('place_id_seq', (SELECT max(id) FROM "public"."place"))`);
        await queryRunner.query(`ALTER TABLE "public"."place" ALTER COLUMN "id" SET DEFAULT nextval('public.place_id_seq')`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."user"."id" IS NULL`);
        await queryRunner.query(`CREATE SEQUENCE "public"."user_id_seq" OWNED BY "public"."user"."id"`);
        await queryRunner.query(`SELECT SETVAL('user_id_seq', (SELECT max(id) FROM "public"."user"))`);
        await queryRunner.query(`ALTER TABLE "public"."user" ALTER COLUMN "id" SET DEFAULT nextval('public.user_id_seq')`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."user"."roles" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."glider"."id" IS NULL`);
        await queryRunner.query(`CREATE SEQUENCE "public"."glider_id_seq" OWNED BY "public"."glider"."id"`);
        await queryRunner.query(`SELECT SETVAL('glider_id_seq', (SELECT max(id) FROM "public"."glider"))`);
        await queryRunner.query(`ALTER TABLE "public"."glider" ALTER COLUMN "id" SET DEFAULT nextval('public.glider_id_seq')`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."flight"."id" IS NULL`);
        await queryRunner.query(`CREATE SEQUENCE "public"."flight_id_seq" OWNED BY "public"."flight"."id"`);
        await queryRunner.query(`SELECT SETVAL('flight_id_seq', (SELECT max(id) FROM "public"."flight"))`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ALTER COLUMN "id" SET DEFAULT nextval('public.flight_id_seq')`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."flight"."timestamp" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."news"."id" IS NULL`);
        await queryRunner.query(`CREATE SEQUENCE "public"."news_id_seq" OWNED BY "public"."news"."id"`);
        await queryRunner.query(`SELECT SETVAL('news_id_seq', (SELECT max(id) FROM "public"."news"))`);
        await queryRunner.query(`ALTER TABLE "public"."news" ALTER COLUMN "id" SET DEFAULT nextval('public.news_id_seq')`);
        await queryRunner.query(`CREATE INDEX "idx_16603_user_id" ON "public"."place" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16603_primary" ON "public"."place" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_idx_ed85f2a29d842b9b0dfefaba34" ON "public"."user" ("username_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_uniq_8d93d64992fc23a8" ON "public"."user" ("username_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_primary" ON "public"."user" ("id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_uniq_8d93d649a0d96fbf" ON "public"."user" ("email_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_idx_846d5513f58dc765ecc299582a" ON "public"."user" ("email_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_email" ON "public"."user" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16606_idx_e12875dfb3b1d92d7d7c5377e2" ON "public"."user" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_16593_user_id" ON "public"."glider" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16593_primary" ON "public"."glider" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_16586_user_id" ON "public"."flight" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_16586_start_id" ON "public"."flight" ("start_id") `);
        await queryRunner.query(`CREATE INDEX "idx_16586_landing_id" ON "public"."flight" ("landing_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16586_primary" ON "public"."flight" ("id") `);
        await queryRunner.query(`CREATE INDEX "idx_16586_glider_id" ON "public"."flight" ("glider_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_16597_primary" ON "public"."news" ("id") `);
        await queryRunner.query(`ALTER TABLE "public"."place" ADD CONSTRAINT "FK_9fc0012ac9ba524ad1ff9fcd476" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."glider" ADD CONSTRAINT "FK_488f52a7113733d72419d954368" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "FK_0fc6e13057b8e23f8293b909d9c" FOREIGN KEY ("glider_id") REFERENCES "public"."glider"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "FK_fa0d02650d9ea2b4b92887782c6" FOREIGN KEY ("landing_id") REFERENCES "public"."place"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "FK_004ba6abb3df28176e5101a16f1" FOREIGN KEY ("start_id") REFERENCES "public"."place"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "FK_bc027109ad4c8ce3f5849423f71" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "FK_bc027109ad4c8ce3f5849423f71"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "FK_004ba6abb3df28176e5101a16f1"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "FK_fa0d02650d9ea2b4b92887782c6"`);
        await queryRunner.query(`ALTER TABLE "public"."flight" DROP CONSTRAINT "FK_0fc6e13057b8e23f8293b909d9c"`);
        await queryRunner.query(`ALTER TABLE "public"."glider" DROP CONSTRAINT "FK_488f52a7113733d72419d954368"`);
        await queryRunner.query(`ALTER TABLE "public"."place" DROP CONSTRAINT "FK_9fc0012ac9ba524ad1ff9fcd476"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16597_primary"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16586_glider_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16586_primary"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16586_landing_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16586_start_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16586_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16593_primary"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16593_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_idx_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_idx_846d5513f58dc765ecc299582a"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_uniq_8d93d649a0d96fbf"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_primary"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_uniq_8d93d64992fc23a8"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16606_idx_ed85f2a29d842b9b0dfefaba34"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16603_primary"`);
        await queryRunner.query(`DROP INDEX "public"."idx_16603_user_id"`);
        await queryRunner.query(`ALTER TABLE "public"."news" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "public"."news_id_seq"`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."news"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."flight"."timestamp" IS NULL`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "public"."flight_id_seq"`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."flight"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "public"."glider" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "public"."glider_id_seq"`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."glider"."id" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."user"."roles" IS '(DC2Type:array)'`);
        await queryRunner.query(`ALTER TABLE "public"."user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "public"."user_id_seq"`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."user"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "public"."place" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "public"."place_id_seq"`);
        await queryRunner.query(`COMMENT ON COLUMN "public"."place"."id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "public"."glider" RENAME COLUMN "nbFlights" TO "nbflights"`);
        await queryRunner.query(`CREATE INDEX "idx_17293_glider_id" ON "public"."flight" ("glider_id") `);
        await queryRunner.query(`CREATE INDEX "idx_17293_start_id" ON "public"."flight" ("start_id") `);
        await queryRunner.query(`CREATE INDEX "idx_17293_user_id" ON "public"."flight" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_17293_landing_id" ON "public"."flight" ("landing_id") `);
        await queryRunner.query(`CREATE INDEX "idx_17300_user_id" ON "public"."glider" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_17313_uniq_8d93d64992fc23a8" ON "public"."user" ("username_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_17313_idx_846d5513f58dc765ecc299582a" ON "public"."user" ("email_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_17313_uniq_8d93d649a0d96fbf" ON "public"."user" ("email_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_17313_email" ON "public"."user" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_17313_idx_ed85f2a29d842b9b0dfefaba34" ON "public"."user" ("username_canonical") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_17313_idx_e12875dfb3b1d92d7d7c5377e2" ON "public"."user" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_17310_user_id" ON "public"."place" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "fk_d4c2b80985553b9400b9898a313" FOREIGN KEY ("landing_id") REFERENCES "public"."place"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "fk_bec9140d8e19f641e75f5b340c6" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "fk_6e3cf0bb9b6729108a3b1dc2564" FOREIGN KEY ("start_id") REFERENCES "public"."place"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."flight" ADD CONSTRAINT "fk_5cf201db9ec080554a510914359" FOREIGN KEY ("glider_id") REFERENCES "public"."glider"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."glider" ADD CONSTRAINT "fk_19c3b7c7e703ff604bb3e1cfa73" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE "public"."place" ADD CONSTRAINT "fk_f932bcc7e17e3673cf5da5d828c" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE RESTRICT ON UPDATE RESTRICT`);
    }

}
