version: '3.1'

volumes:
  postgres-data:

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: flightbook_dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: flightbook_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@flightbook.ch
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "7180:80"