name: feature branch pipeline

on:
  push:
    branches-ignore:
      - master

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - 
        name: Install dependencies
        run: npm install
      - 
        name: Run tests
        run: npm run test
  it_test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - 
        name: Install dependencies
        run: npm install
      - 
        name: Run tests
        run: npm run test:it